import type { FraudDetectionResult } from "./types";

export const MOCK_FRAUD_RESULTS: Record<string, FraudDetectionResult> = {
  healthcare: {
    risk_level: "high",
    risk_label: "高危",
    scene_type: "医保社保诈骗",
    confidence: 96,
    red_flags: [
      "短信里带了链接",
      "催你马上操作",
      "真正官方通知不会这样逼人",
    ],
    plain_explain: {
      title: "这是骗你点链接的短信",
      what_happened: "有人冒充医保部门，催你点链接核验信息。",
      why_dangerous: "点进去后可能要你填卡号、验证码和密码。",
    },
    next_actions: {
      dont: ["不要点短信里的链接", "不要填银行卡信息", "不要把验证码告诉别人"],
      do: ["直接删除短信", "拨打官方电话核实", "转发给家人一起看"],
    },
    family_message: "我收到一条医保短信，带链接催我马上验证。你帮我看一下是不是骗子。",
    need_more_info: false,
    follow_up_question: "不用补充了。",
  },
  fake_customer_service: {
    risk_level: "high",
    risk_label: "高危",
    scene_type: "冒充客服退款",
    confidence: 94,
    red_flags: [
      "让你加微信",
      "催你马上处理",
      "说双倍赔偿很不正常",
    ],
    plain_explain: {
      title: "这是冒充客服的骗法",
      what_happened: "有人假装客服，说快递丢了要赔钱。",
      why_dangerous: "一旦加微信，对方就可能继续引导你转账。",
    },
    next_actions: {
      dont: ["不要加对方微信", "不要扫陌生二维码", "不要泄露银行卡号"],
      do: ["去订单里查官方客服", "让家人帮你核对订单", "保留聊天记录"],
    },
    family_message: "有人说快递丢了要我加微信赔钱，我觉得不对劲，你帮我看看。",
    need_more_info: false,
    follow_up_question: "不用补充了。",
  },
  fake_relative: {
    risk_level: "high",
    risk_label: "高危",
    scene_type: "冒充亲友借钱",
    confidence: 95,
    red_flags: ["换号后急着要钱", "不让打电话确认", "语气不符合亲人习惯"],
    plain_explain: {
      title: "很像冒充家人的骗子",
      what_happened: "有人假装是你孩子，说手机坏了要借钱。",
      why_dangerous: "真家人会先把事情说清楚，不会催你马上转账。",
    },
    next_actions: {
      dont: ["不要转钱", "不要告诉对方银行卡信息", "不要只靠微信确认"],
      do: ["直接打原号码确认", "发语音核对身份", "没确认前一分钱都别转"],
    },
    family_message: "有人发消息说是我孩子，要我转5000元，我先没转，你帮我确认一下。",
    need_more_info: false,
    follow_up_question: "不用补充了。",
  },
  fake_prize: {
    risk_level: "high",
    risk_label: "高危",
    scene_type: "虚假中奖",
    confidence: 97,
    red_flags: ["中奖先交钱", "发奖品前要先付款", "运费不可能这么高"],
    plain_explain: {
      title: "这是假的中奖信息",
      what_happened: "有人说你中奖了，但要先交运费和保险费。",
      why_dangerous: "真中奖不会先找你要钱，交了也拿不回。",
    },
    next_actions: {
      dont: ["不要交任何钱", "不要填地址", "不要给个人信息"],
      do: ["直接删掉消息", "记住先交钱就是骗子", "告诉家人别信"],
    },
    family_message: "我收到中奖消息，对方要我先付运费，我觉得像骗子。",
    need_more_info: false,
    follow_up_question: "不用补充了。",
  },
  police_scam: {
    risk_level: "high",
    risk_label: "高危",
    scene_type: "冒充公检法",
    confidence: 98,
    red_flags: ["要求转到安全账户", "说涉案让你害怕", "假装官方催你保密"],
    plain_explain: {
      title: "这是假公检法",
      what_happened: "有人冒充公检法，说你涉案要先转钱。",
      why_dangerous: "真公检法不会让你转账到安全账户。",
    },
    next_actions: {
      dont: ["不要转钱", "不要说验证码", "不要被吓住就照做"],
      do: ["直接挂断", "找最近派出所核实", "告诉家人"],
    },
    family_message: "刚接到自称公检法的电话，让我转钱，我没转，你帮我看看。",
    need_more_info: false,
    follow_up_question: "不用补充了。",
  },
  brushing_scam: {
    risk_level: "high",
    risk_label: "高危",
    scene_type: "刷单返利",
    confidence: 95,
    red_flags: ["先给小钱再诱导大钱", "让你加群", "说轻松赚钱"],
    plain_explain: {
      title: "这是刷单骗局",
      what_happened: "有人说在家做任务就能赚钱。",
      why_dangerous: "先让你尝到甜头，后面就会骗你垫钱。",
    },
    next_actions: {
      dont: ["不要加群", "不要垫钱做任务", "不要信日入几百"],
      do: ["直接忽略消息", "记住轻松赚钱大多是骗子"],
    },
    family_message: "有人说在家做任务能赚钱，我怀疑是骗局。",
    need_more_info: false,
    follow_up_question: "不用补充了。",
  },
  investment_scam: {
    risk_level: "high",
    risk_label: "高危",
    scene_type: "虚假投资",
    confidence: 94,
    red_flags: ["保证稳赚不赔", "拉群带单", "要求尽快投入"],
    plain_explain: {
      title: "这是投资骗局",
      what_happened: "有人说有内部消息，跟着投就能赚钱。",
      why_dangerous: "前面的小利是诱饵，后面大概率拿不回钱。",
    },
    next_actions: {
      dont: ["不要投钱", "不要进群", "不要信稳赚不赔"],
      do: ["删掉消息", "真要投资就去正规机构问"],
    },
    family_message: "有人拉我进投资群，说稳赚不赔，我觉得不靠谱。",
    need_more_info: false,
    follow_up_question: "不用补充了。",
  },
  fake_community: {
    risk_level: "high",
    risk_label: "高危",
    scene_type: "虚假通知",
    confidence: 89,
    red_flags: ["索要身份证照片", "网址不像官方", "用福利逼你上传资料"],
    plain_explain: {
      title: "这是假社区通知",
      what_happened: "有人假装社区工作人员，让你上传身份证照片。",
      why_dangerous: "身份证照片可能被拿去做坏事。",
    },
    next_actions: {
      dont: ["不要上传身份证照片", "不要点陌生链接", "不要填个人资料"],
      do: ["去社区当面问", "电话核实", "转给家人确认"],
    },
    family_message: "收到社区通知，要我上传身份证照片，我没传，先问问你。",
    need_more_info: false,
    follow_up_question: "不用补充了。",
  },
  generic_suspicious: {
    risk_level: "medium",
    risk_label: "可疑",
    scene_type: "其他",
    confidence: 66,
    red_flags: ["内容有点不对劲", "催得有点急"],
    plain_explain: {
      title: "这条消息有点可疑",
      what_happened: "你收到的信息里有些地方不太对。",
      why_dangerous: "先别急着照做，最好让家人一起看。",
    },
    next_actions: {
      dont: ["先别按它说的做", "不要随便转钱"],
      do: ["转给家人看", "等确认后再决定"],
    },
    family_message: "我收到一条消息，看不太懂，怕有问题，你帮我看下。",
    need_more_info: true,
    follow_up_question: "把完整内容发我看看行吗？",
  },
  safe_notification: {
    risk_level: "safe",
    risk_label: "安全",
    scene_type: "正常通知",
    confidence: 90,
    red_flags: [],
    plain_explain: {
      title: "这是正常通知",
      what_happened: "这是一条普通服务提醒，没有危险信号。",
      why_dangerous: "没有明显风险。",
    },
    next_actions: {
      dont: [],
      do: ["可以放心查看", "不用特别处理", "不放心可让家人看一下"],
    },
    family_message: "",
    need_more_info: false,
    follow_up_question: "不用补充了。",
  },
};
